"""empty message

Revision ID: 23e1c412f2d8
Revises: 94bd48ccb82c
Create Date: 2021-10-06 15:03:00.215001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23e1c412f2d8'
down_revision = '94bd48ccb82c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lecturer', sa.Column('person', sa.Integer(), nullable=True, foreign_key=True))
    op.create_unique_constraint(None, 'person', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'person', type_='unique')
    op.drop_column('lecturer', 'person')
    # ### end Alembic commands ###
