"""empty message

Revision ID: 8d803c06bbc2
Revises: 23e1c412f2d8
Create Date: 2021-10-07 07:22:02.938298

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8d803c06bbc2'
down_revision = '23e1c412f2d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin', sa.Column('photo', sa.String(length=100), nullable=True))
    op.add_column('affectation', sa.Column('lecturer_id', sa.String(length=15), nullable=False))
    op.add_column('affectation', sa.Column('course_id', sa.String(length=15), nullable=False))
    op.create_foreign_key(None, 'affectation', 'course', ['course_id'], ['id'])
    op.create_foreign_key(None, 'affectation', 'lecturer', ['lecturer_id'], ['matricule'])
    op.add_column('attendance', sa.Column('student_id', sa.String(length=15), nullable=False))
    op.create_foreign_key(None, 'attendance', 'student', ['student_id'], ['matricule'])
    op.add_column('department', sa.Column('faculty_id', sa.String(length=15), nullable=False))
    op.create_foreign_key(None, 'department', 'faculty', ['faculty_id'], ['id'])
    op.add_column('lecturer', sa.Column('person_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'lecturer', 'person', ['person_id'], ['id'])
    op.drop_column('lecturer', 'person')
    op.add_column('level', sa.Column('department_id', sa.String(length=15), nullable=False))
    op.create_foreign_key(None, 'level', 'department', ['department_id'], ['id'])
    op.drop_index('id', table_name='person')
    op.add_column('school_fees', sa.Column('student_fid', sa.String(length=15), nullable=False))
    op.create_foreign_key(None, 'school_fees', 'student', ['student_fid'], ['matricule'])
    op.add_column('student', sa.Column('person_sid', sa.Integer(), nullable=False))
    op.add_column('student', sa.Column('faculty_sid', sa.String(length=15), nullable=False))
    op.create_foreign_key(None, 'student', 'faculty', ['faculty_sid'], ['id'])
    op.create_foreign_key(None, 'student', 'person', ['person_sid'], ['id'])
    op.add_column('type', sa.Column('attendance_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'type', 'attendance', ['attendance_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'type', type_='foreignkey')
    op.drop_column('type', 'attendance_id')
    op.drop_constraint(None, 'student', type_='foreignkey')
    op.drop_constraint(None, 'student', type_='foreignkey')
    op.drop_column('student', 'faculty_sid')
    op.drop_column('student', 'person_sid')
    op.drop_constraint(None, 'school_fees', type_='foreignkey')
    op.drop_column('school_fees', 'student_fid')
    op.create_index('id', 'person', ['id'], unique=False)
    op.drop_constraint(None, 'level', type_='foreignkey')
    op.drop_column('level', 'department_id')
    op.add_column('lecturer', sa.Column('person', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'lecturer', type_='foreignkey')
    op.drop_column('lecturer', 'person_id')
    op.drop_constraint(None, 'department', type_='foreignkey')
    op.drop_column('department', 'faculty_id')
    op.drop_constraint(None, 'attendance', type_='foreignkey')
    op.drop_column('attendance', 'student_id')
    op.drop_constraint(None, 'affectation', type_='foreignkey')
    op.drop_constraint(None, 'affectation', type_='foreignkey')
    op.drop_column('affectation', 'course_id')
    op.drop_column('affectation', 'lecturer_id')
    op.drop_column('admin', 'photo')
    # ### end Alembic commands ###
