"""empty message

Revision ID: d5b1427f099b
Revises: 8d803c06bbc2
Create Date: 2021-10-08 23:39:18.732183

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd5b1427f099b'
down_revision = '8d803c06bbc2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin', sa.Column('status', sa.Boolean(), nullable=True))
    op.drop_column('admin', 'etat')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin', sa.Column('etat', mysql.VARCHAR(length=10), nullable=True))
    op.drop_column('admin', 'status')
    # ### end Alembic commands ###
