"""empty message

Revision ID: d70120d154cd
Revises: d5b1427f099b
Create Date: 2021-10-08 23:46:14.921428

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd70120d154cd'
down_revision = 'd5b1427f099b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin', sa.Column('role', sa.String(length=12), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admin', 'role')
    # ### end Alembic commands ###
